### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/Osprey#6]

**Comment by jesterKing** [comment]
Are you thinking of block definitions and block instances here?

**Comment by darbyjohnston** [comment]
Hi, I was thinking of the Rhino "Group" command:
http://docs.mcneel.com/rhino/6/help/en-us/commands/group.htm

Though I wasn't sure if it needed any special processing by a renderer? Block instances should be fairly well supported though there may still be some bugs with material assignments.

**Comment by jesterKing** [comment]
Groups aren't an object type. You can think of them more as selection groups.

**Comment by darbyjohnston** [comment]
Got it, thanks, I'll close this issue then.
